In [1]:
import numpy as np
from sklearn import datasets
#http://stackoverflow.com/questions/11114225/installing-scipy-and-numpy-using-pip

#https://pythondatalab.wordpress.com/machine-learning/7-logistic-regression/

#https://pythondatalab.wordpress.com/

In [2]:
# Load the Pima Indians diabetes dataset from CSV URL
import numpy as np
import urllib
import pandas as pd
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data'
raw_data = urllib.request.urlopen(url)
# load the CSV file as a numpy matrix
dataset = np.loadtxt(raw_data, delimiter=",")
print(dataset.shape)
# separate the data from the target attributes
X = dataset[:,0:7]
y = dataset[:,8]

(768, 9)


In [20]:
raw_data = urllib.request.urlopen(url)


In [9]:
dir(urllib)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'error',
 'parse',
 'request',
 'response']

In [17]:
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data'

In [18]:
print(url)

http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data


In [19]:
raw_data = urllib.request.urlopen(url)

In [21]:
dataset = np.loadtxt(raw_data, delimiter=",")
print(dataset.shape)
# separate the data from the target attributes
X = dataset[:,0:7]
y = dataset[:,8]

(768, 9)


In [22]:
type(raw_data)

http.client.HTTPResponse

In [23]:
dataset

array([[   6.   ,  148.   ,   72.   , ...,    0.627,   50.   ,    1.   ],
       [   1.   ,   85.   ,   66.   , ...,    0.351,   31.   ,    0.   ],
       [   8.   ,  183.   ,   64.   , ...,    0.672,   32.   ,    1.   ],
       ..., 
       [   5.   ,  121.   ,   72.   , ...,    0.245,   30.   ,    0.   ],
       [   1.   ,  126.   ,   60.   , ...,    0.349,   47.   ,    1.   ],
       [   1.   ,   93.   ,   70.   , ...,    0.315,   23.   ,    0.   ]])

In [24]:
#First 25 Outcomes
y[:25]

array([ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  1.])

In [25]:
from sklearn.linear_model import LogisticRegression
LogReg = LogisticRegression()

In [26]:
LogReg.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0)

In [27]:
myModel = LogReg.fit(X,y)

In [28]:
print(myModel)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0)


In [29]:
myModel.predict(X)[:10]

array([ 1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.])

In [30]:
y[:10]

array([ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.])